### PR TITLE
README: add testing badges

### PR DESCRIPTION
**Pull request by waldyrious**
On hold until the tests are actually green

### CODE REVIEW

**Comment by waldyrious** [comment]
See http://pkg.julialang.org/detail/Tau.html and http://pkg.julialang.org/pulse.html

**Comment by waldyrious** [comment]
@Aerlinger, would you mind giving me the necessary permissions to set up Travis for this repo? It would be nice if we could test PRs before merging them.

**Comment by waldyrious** [comment]
Until the necessary tokens are set on this repo, here are the results using [my fork](https://github.com/waldyrious/Tau.jl):

Travis:  [Travis](https://travis-ci.org/waldyrious/Tau.jl)
Appveyor: [Appveyor](https://ci.appveyor.com/project/waldyrious/tau-jl-4rqf9/branch/master)
Coveralls: [Coveralls](https://coveralls.io/github/waldyrious/Tau.jl)
Codecov: [Codecov](https://codecov.io/gh/waldyrious/Tau.jl)

**Comment by waldyrious** [comment]
@Aerlinger I was planning on not merging this until the services were actually configured. Are you going to set up Travis, Appveyor, etc for this repo? I can do that if you prefer, but I don't currently have the permissions to do so.

**Comment by Aerlinger** [comment]
I set up Travis for the repo just now, but I don't think I can add Travis
permissions for you directly.

**Comment by waldyrious** [comment]
You're right. Reading the help pages linked from https://help.github.com/articles/what-are-the-different-access-permissions/, it appears that the only way one more than one person can have access to the repository settings, is if the repository is under an organization.

At this point I'd bring up a proposal I made [before](https://github.com/Aerlinger/Tau.jl/pull/8#issuecomment-267782812): would you consider the possibility of getting Tau.jl under the umbrella of the @JuliaMath organization? I understand if you'd rather not, but I thought I'd make sure, since you haven't mentioned a preference either way so far.

**Comment by Aerlinger** [comment]
Yeah, I need to be a member of JuliaMath before I can transfer the
repository. I'll ping them for an invite, but if you have the ability to
invite, that'd be helpful too.

**Comment by waldyrious** [comment]
Gee, I had forgotten about [that detail](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization). I never understood the reasoning for that, but in any case, I'm not in there either. Perhaps @tkelman could help us out -- he's been very helpful and responsive when I submitted the recent changes in this repo to METADATA.jl.

**Comment by tkelman** [comment]
Okay. Try not to mess with any of the other repos there without going through PR's etc. Github/Travis/etc permissions aren't the most granular things.

**Comment by Aerlinger** [comment]
Thanks @tkelman. I moved the repo just now.

**Comment by waldyrious** [comment]
@tkelman could you invite me as well? I still don't have access to this repo's settings, and I'd like to set up the integrations for the remaining badges.

**Pull request merged**
